/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 24-May-2019 14:10:34
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 15
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const float NUM[MWSPT_NSEC][3] = {
  {
    0.01833779129301,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
    0.01733754008414,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
    0.01650552959194,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
    0.01584566450423,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
    0.01535608591032,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
    0.01503286624417,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
    0.01487232244471,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const float DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.86747235838,   0.9408235235521 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.765609410211,   0.8349595705477 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.680879653435,   0.7469017718028 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.613680731174,   0.6770633891905 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.563823336857,   0.6252476804987 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.530907497509,   0.5910389624854 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.514558139889,   0.5740474296673 
  },
  {
                   1,                 0,                 0 
  }
};
